name: Feed Cron

on:
  schedule:
    - cron: "0 * * * 9999" # UTC
  workflow_dispatch:

jobs:
  get-feed:
    runs-on: ubuntu-latest
    env:
      NOTION_KEY: ${{ secrets.NOTION_KEY }}
      NOTION_READER_DATABASE_ID: ${{ secrets.NOTION_READER_DATABASE_ID }}
      NOTION_FEEDER_DATABASE_ID: ${{ secrets.NOTION_FEEDER_DATABASE_ID }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Update Notion Feed
        run: node dist/bundle.cjs
